### PR TITLE
Implement hardware vertical scroll

### PR DESCRIPTION
**Pull request by twitchyliquid64**

### CODE REVIEW

**Comment by yuri91** [comment]
Thanks a lot for the PR!

This is a nice feature I wanted to add from the start but never got to do.

**Comment by jessebraham** [comment]
Hello @yuri91, sorry to be a bother but whenever it's convenient would you be able to publish a release that includes this feature please? It is being used in an example for our [Wio Terminal board support package](https://github.com/atsamd-rs/atsamd/pull/285) but we need to eliminate the remaining git dependencies before we're able to do a release. Thanks!

**Comment by yuri91** [comment]
Sure, I will do it by the end of the week (if not, feel free to ping me again, I am pretty busy these days and I may forget)

**Comment by yuri91** [comment]
@jessebraham  0.4.1 is out on [crates.io](https://crates.io/crates/ili9341) :tada:

**Comment by jessebraham** [comment]
Awesome, thank you so much!

**Pull request merged**
