### PR TITLE
Do not hardcode display size

### PR DESCRIPTION
**Pull request by almusil**
ili driver family is pretty generic with support
of multiple display sizes. By having width and size
as parameter this driver can support broader range
of ili displays.

### CODE REVIEW

**Comment by almusil** [comment]
@yuri91 Hello, can you please take a look?

**Comment by jamwaffles** [comment]
The SSD1306 crate uses an enum to define different display sizes in a safe way. Would that be a consideration for the ILI9341 driver or is the resolution completely variable?

**Comment by almusil** [comment]
I was able to find several drivers and their sizes:
ili9341: 240x320
ili9486: 320x480
ili9486l: 320x480
ili9488: 320x480

So it seems that it should be possible to have it via enum. I'll rework this patch, thanks.

**Comment by yuri91** [comment]
Hi!

This PR seems good to me.

Just a few considerations:

- Since the driver will technically not be about only ili9341 anymore, should we change the crate name? (maybe I will open an issue about this)

- This is a breaking change, which is fine. But maybe it could make sense to leave the current size as default? (Especially if we keep the current crate name).

Let me know what you think

**Comment by almusil** [comment]
> Hi!
> 
> This PR seems good to me.

Hi, 
thank for the review.

> Just a few considerations:
> 
>     * Since the driver will technically not be about only ili9341 anymore, should we change the crate name? (maybe I will open an issue about this)
> 
>     * This is a breaking change, which is fine. But maybe it could make sense to leave the current size as default? (Especially if we keep the current crate name).
> 

The breaking change with rename in single release sounds fine to me, 0.4.1 on crates will work as before. So moving to 0.5 
after the crate is renamed and doc updated is fine as well IMO. Maybe having branch 0.4 that will have 0.4.2 release with note that the crate has moved to different name? 

> 
> Let me know what you think

**Pull request merged**
